/**:  
  ros__parameters:
    carla/sync : false
    carla/sync_with_delay : true
    period/velocity_planner : 90
    delay/velocity_planner : 150
    period/path_planner : 30
    delay/path_planner : 30
