/**:  
  ros__parameters:
    carla/sync : true
    carla/sync_with_delay : false
    period/velocity_planner : 30
    delay/velocity_planner : 100
    period/path_planner : 30
    delay/path_planner : 50
